# Generated by Django 5.1.7 on 2026-06-20 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="案件标题")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="案件描述"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "案件",
                "verbose_name_plural": "案件",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("platform", "平台客服版"),
                            ("regulatory", "监管投诉版"),
                            ("arbitration", "仲裁准备版"),
                        ],
                        default="platform",
                        max_length=20,
                        verbose_name="模板类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complaint_templates",
                        to="api.case",
                        verbose_name="所属案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "投诉模板",
                "verbose_name_plural": "投诉模板",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="如 E1、E2", max_length=20, verbose_name="证据编号"
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        help_text="如 订单页/聊天记录/物流页/客服回复",
                        max_length=50,
                        verbose_name="证据类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="证据描述")),
                ("source_time", models.DateTimeField(verbose_name="证据发生时间")),
                (
                    "has_sensitive_info",
                    models.BooleanField(default=False, verbose_name="是否含敏感信息"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="api.case",
                        verbose_name="所属案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "证据",
                "verbose_name_plural": "证据",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TimelineNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="发生时间")),
                ("event", models.TextField(verbose_name="事件描述")),
                (
                    "related_evidence_codes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="逗号分隔，如 E1,E2",
                        max_length=200,
                        verbose_name="关联证据编号",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_nodes",
                        to="api.case",
                        verbose_name="所属案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "时间线节点",
                "verbose_name_plural": "时间线节点",
                "ordering": ["order", "datetime"],
            },
        ),
    ]
