# Generated by Django 5.1.7 on 2026-06-29 12:43

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="extracted_text",
            field=models.TextField(blank=True, default="", verbose_name="OCR 抽取文本"),
        ),
        migrations.AddField(
            model_name="evidence",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.evidence_image_path,
                verbose_name="证据图片",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ocr_status",
            field=models.CharField(
                default="pending",
                help_text="pending/done/failed",
                max_length=20,
                verbose_name="OCR 状态",
            ),
        ),
        migrations.AddField(
            model_name="timelinenode",
            name="auto_generated",
            field=models.BooleanField(default=False, verbose_name="是否自动生成"),
        ),
        migrations.CreateModel(
            name="ComplaintTemplateRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("platform", "平台客服版"),
                            ("regulatory", "监管投诉版"),
                            ("arbitration", "仲裁准备版"),
                        ],
                        max_length=20,
                        verbose_name="模板类型",
                    ),
                ),
                ("rule_title", models.TextField(verbose_name="标题 Jinja2 源码")),
                ("rule_content", models.TextField(verbose_name="正文 Jinja2 源码")),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_rules",
                        to="api.case",
                        verbose_name="所属案件（null 表示全局规则）",
                    ),
                ),
            ],
            options={
                "verbose_name": "投诉模板规则",
                "verbose_name_plural": "投诉模板规则",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="订单号/金额/手机号/地址/时间/承诺话术",
                        max_length=50,
                        verbose_name="字段名",
                    ),
                ),
                (
                    "field_value",
                    models.CharField(max_length=500, verbose_name="字段值"),
                ),
                ("confidence", models.FloatField(default=0.9, verbose_name="置信度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_fields",
                        to="api.evidence",
                        verbose_name="所属证据",
                    ),
                ),
            ],
            options={
                "verbose_name": "抽取字段",
                "verbose_name_plural": "抽取字段",
                "ordering": ["id"],
            },
        ),
    ]
