# Generated by Django 5.1.7 on 2026-07-03 09:16

import api.models
import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_evidence_extracted_text_evidence_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("shopping", "网购纠纷"),
                    ("service", "服务违约"),
                    ("secondhand", "二手交易"),
                    ("other", "其他"),
                ],
                default="shopping",
                max_length=20,
                verbose_name="纠纷类型",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="status",
            field=django_fsm.FSMField(
                default="draft", max_length=50, protected=True, verbose_name="案件状态"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="evidence",
            name="mask_status",
            field=models.CharField(
                default="none",
                help_text="none/pending/done",
                max_length=20,
                verbose_name="打码状态",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="masked_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.masked_image_path,
                verbose_name="打码后图片",
            ),
        ),
        migrations.CreateModel(
            name="CaseStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="原状态"
                    ),
                ),
                ("to_status", models.CharField(max_length=20, verbose_name="目标状态")),
                (
                    "remark",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="api.case",
                        verbose_name="所属案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "案件状态日志",
                "verbose_name_plural": "案件状态日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
