# Generated by Django 5.1.7 on 2026-07-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_case_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseTypePreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("shopping", "网购纠纷"),
                            ("service", "服务违约"),
                            ("secondhand", "二手交易"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="纠纷类型",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="预设名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="预设说明"),
                ),
                (
                    "evidence_types",
                    models.JSONField(
                        default=list,
                        help_text="证据类型列表",
                        verbose_name="证据类型建议",
                    ),
                ),
                (
                    "timeline_skeleton",
                    models.JSONField(
                        default=list,
                        help_text="时间线节点骨架",
                        verbose_name="时间线骨架",
                    ),
                ),
                (
                    "complaint_template",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Jinja2 模板",
                        verbose_name="投诉模板",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "案件类型预设",
                "verbose_name_plural": "案件类型预设",
                "ordering": ["case_type", "id"],
            },
        ),
        migrations.AlterField(
            model_name="timelinenode",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="发生时间"),
        ),
    ]
