# Generated by Django 5.1.7 on 2026-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_timeline_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="thread_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="LangGraph checkpointer 的 thread_id，用于 HITL 状态恢复",
                max_length=100,
                verbose_name="LangGraph Thread ID",
            ),
        ),
    ]
