# Generated by Django 5.1.7 on 2026-07-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_add_thread_id_to_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="evidence_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="chat_screenshot/product_order/logistics_tracking/payment_record/invoice/other",
                max_length=50,
                verbose_name="LLM分类",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="ocr_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="视觉预分类生成的100-200字摘要",
                verbose_name="OCR摘要",
            ),
        ),
        migrations.AddField(
            model_name="extractedfield",
            name="field_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="订单信息/支付信息/物流信息/发票信息/联系信息/时间信息/其他",
                max_length=50,
                verbose_name="字段分类",
            ),
        ),
        migrations.AddField(
            model_name="extractedfield",
            name="source_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="OCR文本MD5，用于缓存比对避免重复抽取",
                max_length=32,
                verbose_name="源文本哈希",
            ),
        ),
    ]
