# Generated by Django 5.1.7 on 2026-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_v9_preclassify_summary_field_category_source_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="LawArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "law_name",
                    models.CharField(
                        db_index=True,
                        help_text="如：中华人民共和国消费者权益保护法",
                        max_length=100,
                        verbose_name="法律名称",
                    ),
                ),
                (
                    "article_number",
                    models.CharField(
                        db_index=True,
                        help_text="如：第五十五条（保持官方原文格式）",
                        max_length=20,
                        verbose_name="条文编号",
                    ),
                ),
                (
                    "chapter",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如：第七章 法律责任",
                        max_length=100,
                        verbose_name="章节",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="官方颁布原文，逐字校验", verbose_name="条文内容"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="一句话概括，用于快速检索展示",
                        max_length=200,
                        verbose_name="条文摘要",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("consumer_protection", "消费者权益保护法"),
                            ("e-commerce", "电子商务法"),
                            ("contract", "民法典合同编"),
                            ("quality", "产品质量法"),
                            ("safety", "食品安全法"),
                            ("privacy", "个人信息保护法"),
                            ("platform_rule", "平台规则"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                        verbose_name="法律分类",
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='如：["退一赔三", "欺诈", "三倍赔偿"]',
                        verbose_name="关键词",
                    ),
                ),
                (
                    "applicable_scenarios",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='如：["虚假宣传", "假冒伪劣", "价格欺诈"]',
                        verbose_name="适用场景",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="生效日期"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="现行有效"
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="flk.npc.gov.cn 官方法条 URL，用于溯源校验",
                        max_length=500,
                        verbose_name="数据源URL",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "法律条文",
                "verbose_name_plural": "法律条文",
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="api_lawarti_categor_10a999_idx",
                    ),
                    models.Index(
                        fields=["law_name", "is_active"],
                        name="api_lawarti_law_nam_9db597_idx",
                    ),
                ],
                "unique_together": {("law_name", "article_number")},
            },
        ),
        migrations.CreateModel(
            name="PlatformRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("taobao", "淘宝"),
                            ("tmall", "天猫"),
                            ("jd", "京东"),
                            ("pdd", "拼多多"),
                            ("douyin", "抖音电商"),
                            ("kuaishou", "快手电商"),
                            ("vipshop", "唯品会"),
                            ("suning", "苏宁易购"),
                            ("other", "其他"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="平台",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        help_text="如：延迟发货规则、假货处理规则",
                        max_length=200,
                        verbose_name="规则名称",
                    ),
                ),
                (
                    "issue_type",
                    models.CharField(
                        db_index=True,
                        help_text="如：late_delivery, counterfeit, quality_issue, refund_dispute",
                        max_length=50,
                        verbose_name="问题类型",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="官方规则原文", verbose_name="规则内容"),
                ),
                (
                    "compensation_standard",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="如：订单金额30%赔付，最高不超过500元",
                        verbose_name="赔偿标准",
                    ),
                ),
                (
                    "handling_process",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="投诉处理步骤",
                        verbose_name="处理流程",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="数据源URL"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(blank=True, null=True, verbose_name="生效日期"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="现行有效"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "平台规则",
                "verbose_name_plural": "平台规则",
                "indexes": [
                    models.Index(
                        fields=["platform", "issue_type", "is_active"],
                        name="api_platfor_platfor_f7cdda_idx",
                    )
                ],
                "unique_together": {("platform", "rule_name")},
            },
        ),
    ]
