# Generated by Django 5.1.7 on 2026-07-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_v10_law_article_and_platform_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="case_mode",
            field=models.CharField(
                choices=[("complain", "维权投诉"), ("respond", "商家反证")],
                default="complain",
                max_length=20,
                verbose_name="案件模式",
            ),
        ),
        migrations.AddField(
            model_name="platformrule",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("platform", "平台规则"),
                    ("regulatory", "监管规则"),
                    ("industry", "行业规则"),
                ],
                db_index=True,
                default="platform",
                max_length=20,
                verbose_name="规则类型",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="evidence_category",
            field=models.CharField(
                blank=True,
                default="",
                help_text="chat_screenshot/product_order/logistics_tracking/payment_record/invoice/service_contract/work_record/communication_record/contract_document/medical_record/other",
                max_length=50,
                verbose_name="LLM分类",
            ),
        ),
        migrations.AlterField(
            model_name="platformrule",
            name="platform",
            field=models.CharField(
                choices=[
                    ("taobao", "淘宝"),
                    ("tmall", "天猫"),
                    ("jd", "京东"),
                    ("pdd", "拼多多"),
                    ("douyin", "抖音电商"),
                    ("kuaishou", "快手电商"),
                    ("vipshop", "唯品会"),
                    ("suning", "苏宁易购"),
                    ("meituan", "美团"),
                    ("eleme", "饿了么"),
                    ("ctrip", "携程"),
                    ("keelage", "Keep"),
                    ("classin", "ClassIn"),
                    ("labor_arbitration", "劳动仲裁委"),
                    ("court_small", "法院小额诉讼"),
                    ("medical_dispute", "医疗纠纷调解"),
                    ("other", "其他"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="平台",
            ),
        ),
        migrations.CreateModel(
            name="RespondTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("platform", "平台申诉版"),
                            ("regulatory", "监管申诉版"),
                            ("legal", "法律答辩版"),
                        ],
                        default="platform",
                        max_length=20,
                        verbose_name="答辩类型",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="答辩内容")),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respond_templates",
                        to="api.case",
                        verbose_name="所属案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "反证答辩书",
                "verbose_name_plural": "反证答辩书",
                "ordering": ["id"],
            },
        ),
    ]
