# Generated by Django 5.1.7 on 2026-07-14 19:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def create_user_profile_and_preferences(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('api', 'UserProfile')
    UserPreference = apps.get_model('api', 'UserPreference')

    profiles = []
    preferences = []

    existing_profile_user_ids = set(
        UserProfile.objects.values_list('user_id', flat=True)
    )
    existing_preference_user_ids = set(
        UserPreference.objects.values_list('user_id', flat=True)
    )

    for user in User.objects.all().iterator():
        if user.id not in existing_profile_user_ids:
            profiles.append(
                UserProfile(
                    user_id=user.id,
                    display_name=user.username,
                    bio='',
                    locale='zh-CN',
                    timezone='Asia/Shanghai',
                    email_verified=False,
                )
            )
        if user.id not in existing_preference_user_ids:
            preferences.append(
                UserPreference(
                    user_id=user.id,
                    workflow_reminders=True,
                    export_reminder=True,
                    compact_case_cards=False,
                    default_case_mode='complain',
                    default_template_type='platform',
                )
            )

    if profiles:
        UserProfile.objects.bulk_create(profiles)
    if preferences:
        UserPreference.objects.bulk_create(preferences)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_case_case_mode_platformrule_rule_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow_reminders",
                    models.BooleanField(default=True, verbose_name="工作流提醒"),
                ),
                (
                    "export_reminder",
                    models.BooleanField(default=True, verbose_name="导出安全提醒"),
                ),
                (
                    "compact_case_cards",
                    models.BooleanField(default=False, verbose_name="紧凑案件卡片"),
                ),
                (
                    "default_case_mode",
                    models.CharField(
                        choices=[("complain", "维权投诉"), ("respond", "商家反证")],
                        default="complain",
                        max_length=20,
                        verbose_name="默认案件模式",
                    ),
                ),
                (
                    "default_template_type",
                    models.CharField(
                        choices=[
                            ("platform", "平台客服版"),
                            ("regulatory", "监管投诉版"),
                            ("arbitration", "仲裁准备版"),
                        ],
                        default="platform",
                        max_length=20,
                        verbose_name="默认模板类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户偏好",
                "verbose_name_plural": "用户偏好",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="显示名称"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, default="", verbose_name="个人简介"),
                ),
                (
                    "locale",
                    models.CharField(
                        default="zh-CN", max_length=20, verbose_name="语言地区"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Shanghai", max_length=64, verbose_name="时区"
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(default=False, verbose_name="邮箱已验证"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户资料",
                "verbose_name_plural": "用户资料",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refresh_jti",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="Refresh Token JTI",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="设备名称"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("desktop", "Desktop"),
                            ("other", "Other"),
                        ],
                        default="web",
                        max_length=20,
                        verbose_name="设备类型",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, unpack_ipv4=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="最近活跃时间"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="撤销时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户会话",
                "verbose_name_plural": "用户会话",
                "ordering": ["-last_seen_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "退出当前设备"),
                            ("logout_all", "退出全部设备"),
                            ("change_password", "修改密码"),
                            ("revoke_session", "撤销会话"),
                        ],
                        max_length=32,
                        verbose_name="动作",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, unpack_ipv4=True, verbose_name="IP 地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User Agent"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="附加信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="api.usersession",
                        verbose_name="关联会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "账户审计日志",
                "verbose_name_plural": "账户审计日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "revoked_at"], name="api_userses_user_id_25d2fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "expires_at"], name="api_userses_user_id_f903d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountauditlog",
            index=models.Index(
                fields=["user", "action"], name="api_account_user_id_887e63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountauditlog",
            index=models.Index(
                fields=["created_at"], name="api_account_created_046845_idx"
            ),
        ),
        migrations.RunPython(create_user_profile_and_preferences, noop_reverse),
    ]
