# Generated by Django 5.1.7 on 2026-07-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_lawarticle_category_userpreference_userprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawarticle",
            name="category",
            field=models.CharField(
                choices=[
                    ("consumer_protection", "消费者权益保护法"),
                    ("e-commerce", "电子商务法"),
                    ("contract", "民法典合同编"),
                    ("quality", "产品质量法"),
                    ("safety", "食品安全法"),
                    ("privacy", "个人信息保护法"),
                    ("platform_rule", "平台规则"),
                    ("service", "服务违约相关"),
                    ("medical", "医疗纠纷相关"),
                    ("labor", "劳动争议相关"),
                    ("other", "其他"),
                ],
                db_index=True,
                default="other",
                max_length=30,
                verbose_name="法律分类",
            ),
        ),
    ]
