# Generated by Django 5.1.7 on 2026-07-14 21:53

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_lawarticle_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_display",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.avatar_display_upload_path,
                verbose_name="头像展示图",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_original",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.avatar_original_upload_path,
                verbose_name="头像原图",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="头像更新时间"
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scene",
                    models.CharField(
                        choices=[
                            ("verify_current_email", "验证当前邮箱"),
                            ("change_email", "修改邮箱"),
                        ],
                        max_length=32,
                        verbose_name="验证场景",
                    ),
                ),
                (
                    "target_email",
                    models.EmailField(max_length=254, verbose_name="目标邮箱"),
                ),
                (
                    "code_hash",
                    models.CharField(max_length=255, verbose_name="验证码哈希"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="使用时间"
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="尝试次数"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_challenges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "邮箱验证码挑战",
                "verbose_name_plural": "邮箱验证码挑战",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "scene", "created_at"],
                        name="api_emailve_user_id_04baaf_idx",
                    ),
                    models.Index(
                        fields=["target_email", "scene", "created_at"],
                        name="api_emailve_target__b6c8d4_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="api_emailve_expires_55d00f_idx"
                    ),
                ],
            },
        ),
    ]
