# Generated by Django 5.1.7 on 2026-07-15 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_userprofile_avatar_display_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverificationchallenge",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="验证成功时间"
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationchallenge",
            name="scene",
            field=models.CharField(
                choices=[
                    ("register_email", "注册邮箱"),
                    ("login_email", "登录邮箱"),
                    ("verify_current_email", "验证当前邮箱"),
                    ("change_email", "修改邮箱"),
                ],
                max_length=32,
                verbose_name="验证场景",
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationchallenge",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_verification_challenges",
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
