# Generated by Django 5.1.7 on 2026-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_emailverificationchallenge_verified_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationchallenge",
            name="scene",
            field=models.CharField(
                choices=[
                    ("register_email", "注册邮箱"),
                    ("login_email", "登录邮箱"),
                    ("reset_password", "重置密码"),
                    ("verify_current_email", "验证当前邮箱"),
                    ("change_password_email", "修改密码校验"),
                    ("change_email", "修改邮箱"),
                ],
                max_length=32,
                verbose_name="验证场景",
            ),
        ),
    ]
