# Generated by Django 5.1.7 on 2026-07-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_emailverificationchallenge_scene"),
    ]

    operations = [
        migrations.AddField(
            model_name="complainttemplate",
            name="tone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="LLM 生成的语气（firm/restrained/neutral），由工作流写入",
                max_length=20,
                verbose_name="语气",
            ),
        ),
        migrations.AlterField(
            model_name="complainttemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("platform", "平台客服版"),
                    ("regulatory", "监管投诉版"),
                    ("arbitration", "仲裁准备版"),
                    ("legal", "法律诉讼版"),
                ],
                default="platform",
                max_length=20,
                verbose_name="模板类型",
            ),
        ),
        migrations.AlterField(
            model_name="complainttemplaterule",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("platform", "平台客服版"),
                    ("regulatory", "监管投诉版"),
                    ("arbitration", "仲裁准备版"),
                    ("legal", "法律诉讼版"),
                ],
                max_length=20,
                verbose_name="模板类型",
            ),
        ),
        migrations.AlterField(
            model_name="respondtemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("platform", "平台申诉版"),
                    ("regulatory", "监管申诉版"),
                    ("arbitration", "仲裁答辩版"),
                    ("legal", "法律答辩版"),
                ],
                default="platform",
                max_length=20,
                verbose_name="答辩类型",
            ),
        ),
    ]
