# Generated by Django 5.1.7 on 2026-07-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_add_tone_to_complaint_template_unify_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="is_physical_evidence",
            field=models.BooleanField(
                default=False,
                help_text="标记为纯物证图片（无文字内容），将跳过 OCR 节点",
                verbose_name="纯物证图片",
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="physical_note",
            field=models.CharField(
                blank=True,
                default="",
                help_text="用户提供的物证说明（损坏程度/现场环境/物证特征等）",
                max_length=500,
                verbose_name="物证说明",
            ),
        ),
    ]
