# Generated by Django 5.1.7 on 2026-07-18 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_workflow_pause_and_respond_tone"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowIntervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intervention_type",
                    models.CharField(
                        choices=[
                            ("quality_review", "质量审核"),
                            ("user_pause", "用户暂停"),
                        ],
                        help_text="介入类型：quality_review / user_pause",
                        max_length=32,
                        verbose_name="介入类型",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        help_text="触发阶段，如 extract / evidence_chain / stage_gate_after_extract",
                        max_length=64,
                        verbose_name="触发阶段",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待用户提交"),
                            ("submitted", "已提交"),
                            ("cancelled", "已取消"),
                            ("expired", "已过期"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="介入状态",
                    ),
                ),
                (
                    "base_revision",
                    models.IntegerField(
                        default=0,
                        help_text="触发时的 state.revision，用于冲突检测",
                        verbose_name="触发时 revision",
                    ),
                ),
                (
                    "form_schema",
                    models.JSONField(
                        default=dict,
                        help_text="前端动态表单 schema",
                        verbose_name="表单 schema",
                    ),
                ),
                (
                    "initial_values",
                    models.JSONField(
                        default=dict,
                        help_text="初始值（节点产出供用户编辑）",
                        verbose_name="初始值",
                    ),
                ),
                (
                    "impact",
                    models.JSONField(
                        default=dict,
                        help_text="影响范围描述（下游哪些节点会重跑）",
                        verbose_name="影响范围",
                    ),
                ),
                (
                    "submitted_values",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="用户提交的值（提交后填充）",
                        verbose_name="用户提交值",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="取消时间"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="过期时间（默认 base_revision + 24h）",
                        null=True,
                        verbose_name="过期时间",
                    ),
                ),
                (
                    "created_by_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="创建用户 ID"
                    ),
                ),
                (
                    "submitted_by_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="提交用户 ID"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        help_text="Task 3.1 后改为 workflow_run 外键",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="api.case",
                        verbose_name="关联案件",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流介入记录",
                "verbose_name_plural": "工作流介入记录",
                "db_table": "workflow_intervention",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "status"], name="workflow_in_case_id_84488f_idx"
                    ),
                    models.Index(
                        fields=["intervention_type", "status"],
                        name="workflow_in_interve_45a8ba_idx",
                    ),
                ],
                "unique_together": {
                    ("case", "intervention_type", "stage", "base_revision")
                },
            },
        ),
    ]
