# Generated by Django 5.1.7 on 2026-07-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_workflow_intervention"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedfield",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="用户确认时间（ISO 8601），未确认时为 null",
                null=True,
                verbose_name="确认时间",
            ),
        ),
        migrations.AddField(
            model_name="extractedfield",
            name="user_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="用户在 HITL 校正中确认或修改过该字段则为 True（首次抽取默认 False）",
                verbose_name="用户已确认",
            ),
        ),
    ]
