# Generated by Django 5.1.7 on 2026-07-18 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_extractedfield_user_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowintervention",
            name="case",
            field=models.ForeignKey(
                blank=True,
                help_text="Task 3.1 后冗余字段，从 workflow_run.case 派生",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interventions",
                to="api.case",
                verbose_name="关联案件（冗余）",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thread_id",
                    models.CharField(
                        db_index=True,
                        help_text="格式 case-{case_id}-run-{run_id}，每个 WorkflowRun 独立 thread_id（对齐 langgraph-persistence skill）",
                        max_length=100,
                        unique=True,
                        verbose_name="LangGraph Thread ID",
                    ),
                ),
                (
                    "workflow_version",
                    models.CharField(
                        default="", max_length=20, verbose_name="工作流版本"
                    ),
                ),
                (
                    "state_schema_version",
                    models.IntegerField(default=1, verbose_name="State schema 版本"),
                ),
                (
                    "policy_version",
                    models.CharField(
                        default="", max_length=20, verbose_name="策略版本"
                    ),
                ),
                (
                    "prompt_bundle_version",
                    models.CharField(
                        default="", max_length=20, verbose_name="Prompt bundle 版本"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "运行中"),
                            ("pausing", "暂停中"),
                            ("waiting_user", "等待用户介入"),
                            ("succeeded", "成功完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                        verbose_name="运行状态",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="当前业务阶段",
                    ),
                ),
                (
                    "current_node",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="当前节点名"
                    ),
                ),
                ("progress", models.FloatField(default=0.0, verbose_name="进度")),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=0, verbose_name="State revision"
                    ),
                ),
                (
                    "selected_evidence_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="空列表表示处理案件全部有图证据",
                        verbose_name="选中的证据 ID",
                    ),
                ),
                (
                    "run_options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='如 {"template_type": "platform", "case_mode": "complain"}',
                        verbose_name="运行选项",
                    ),
                ),
                (
                    "quality_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="聚合各阶段质量评分 {stage: {score, coverage, status, blocking_issues}}",
                        verbose_name="质量摘要",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="错误信息"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "started_by_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="发起用户 ID"
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_runs",
                        to="api.case",
                        verbose_name="关联案件",
                    ),
                ),
                (
                    "parent_run",
                    models.ForeignKey(
                        blank=True,
                        help_text="Task 3.3 RetryService fork 出的运行指向原运行",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forked_runs",
                        to="api.workflowrun",
                        verbose_name="父运行（局部重跑 fork 自）",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流运行",
                "verbose_name_plural": "工作流运行",
                "db_table": "workflow_run",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_id",
                    models.IntegerField(
                        blank=True,
                        help_text="产物关联的具体证据 ID（如为多证据聚合产物则为 null）",
                        null=True,
                        verbose_name="关联证据 ID",
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("preclassify_result", "预分类结果"),
                            ("ocr_result", "OCR 结果"),
                            ("classify_result", "分类结果"),
                            ("extract_result", "抽取结果"),
                            ("review_result", "审核结果"),
                            ("evidence_chain", "证据链"),
                            ("complaint_draft", "投诉文书草稿"),
                            ("respond_complaint_draft", "答辩书草稿"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="产物类型",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("material_understanding", "材料理解"),
                            ("fact_checking", "事实核对"),
                            ("case_organization", "案件组织"),
                            ("document_generation", "文书生成"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="所属业务阶段",
                    ),
                ),
                (
                    "node_name",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="生成节点名"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="同类型同证据的版本号（自增）",
                        verbose_name="产物版本",
                    ),
                ),
                (
                    "revision",
                    models.IntegerField(default=0, verbose_name="State revision"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "当前有效"),
                            ("stale", "已过期"),
                            ("superseded", "已替代"),
                        ],
                        db_index=True,
                        default="current",
                        max_length=16,
                        verbose_name="产物状态",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=dict,
                        help_text="节点 NodeResult.data 的快照",
                        verbose_name="产物内容",
                    ),
                ),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="前端卡片展示用摘要 {title, key_metrics, highlights}",
                        verbose_name="业务摘要",
                    ),
                ),
                (
                    "quality",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="NodeResult.quality 的快照 {score, coverage, status, blocking_issues, details}",
                        verbose_name="质量评分",
                    ),
                ),
                (
                    "provenance",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="NodeResult.provenance 列表快照",
                        verbose_name="数据来源",
                    ),
                ),
                (
                    "source_refs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="上游 WorkflowArtifact ID 列表，用于 stale 传播",
                        verbose_name="上游依赖",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="NodeResult.metrics 快照 {duration_ms, model_calls, tokens}",
                        verbose_name="指标",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "stale_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="标记为 stale 的时间",
                        null=True,
                        verbose_name="过期时间",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_artifacts",
                        to="api.case",
                        verbose_name="关联案件（冗余便于查询）",
                    ),
                ),
                (
                    "workflow_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="api.workflowrun",
                        verbose_name="关联运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流产物",
                "verbose_name_plural": "工作流产物",
                "db_table": "workflow_artifact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="workflowintervention",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="case",
            name="active_workflow_run",
            field=models.ForeignKey(
                blank=True,
                help_text="指向案件最近一次活动的工作流运行；保留旧 thread_id / workflow_status 双写兼容",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_cases",
                to="api.workflowrun",
                verbose_name="当前活动运行",
            ),
        ),
        migrations.AddField(
            model_name="workflowintervention",
            name="workflow_run",
            field=models.ForeignKey(
                blank=True,
                help_text="Task 3.1 后替代 case 外键",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interventions",
                to="api.workflowrun",
                verbose_name="关联工作流运行",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowintervention",
            unique_together={
                ("workflow_run", "intervention_type", "stage", "base_revision")
            },
        ),
        migrations.AddIndex(
            model_name="workflowintervention",
            index=models.Index(
                fields=["case", "intervention_type", "stage", "base_revision"],
                name="workflow_in_case_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowintervention",
            index=models.Index(
                fields=["workflow_run", "status"], name="workflow_in_workflo_d6a8cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowrun",
            index=models.Index(
                fields=["case", "status"], name="workflow_ru_case_id_327632_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowrun",
            index=models.Index(
                fields=["status", "started_at"], name="workflow_ru_status_379145_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowartifact",
            index=models.Index(
                fields=["workflow_run", "artifact_type", "status"],
                name="workflow_ar_workflo_04e42d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowartifact",
            index=models.Index(
                fields=["case", "artifact_type", "status"],
                name="workflow_ar_case_id_34f718_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowartifact",
            index=models.Index(
                fields=["evidence_id", "artifact_type"],
                name="workflow_ar_evidenc_2decae_idx",
            ),
        ),
    ]
