# Generated by Django 5.1.7 on 2026-07-18 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_add_workflow_run_and_artifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="complainttemplate",
            name="paragraphs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="文书段落列表，每段含 content / evidence_codes / legal_references / source_regions",
                verbose_name="段落结构",
            ),
        ),
        migrations.AddField(
            model_name="respondtemplate",
            name="paragraphs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="文书段落列表，每段含 content / evidence_codes / legal_references / source_regions",
                verbose_name="段落结构",
            ),
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("complaint", "投诉文书"),
                            ("respond_complaint", "答辩文书"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="文书类型",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(
                        default=1,
                        help_text="同类型同 case 的版本号（自增）",
                        verbose_name="版本号",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="标题"
                    ),
                ),
                ("content", models.TextField(verbose_name="正文内容")),
                (
                    "paragraphs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="段落级结构（含 evidence_codes / legal_references / source_regions）",
                        verbose_name="段落结构",
                    ),
                ),
                (
                    "changelog",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="本版本相对上一版本的变更说明",
                        verbose_name="变更说明",
                    ),
                ),
                (
                    "created_by_type",
                    models.CharField(
                        choices=[
                            ("ai", "AI 生成"),
                            ("user", "用户修改"),
                            ("system", "系统调整"),
                        ],
                        default="ai",
                        max_length=10,
                        verbose_name="创建者类型",
                    ),
                ),
                (
                    "created_by_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="创建者 ID"
                    ),
                ),
                (
                    "workflow_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="生成时的 workflow_version（满足审计需求，对齐 spec.md E 节）",
                        max_length=20,
                        verbose_name="工作流版本",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions",
                        to="api.case",
                        verbose_name="关联案件",
                    ),
                ),
                (
                    "complaint_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="api.complainttemplate",
                        verbose_name="关联投诉模板",
                    ),
                ),
                (
                    "respond_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versions",
                        to="api.respondtemplate",
                        verbose_name="关联答辩模板",
                    ),
                ),
                (
                    "workflow_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_versions",
                        to="api.workflowrun",
                        verbose_name="关联工作流运行",
                    ),
                ),
            ],
            options={
                "verbose_name": "文书版本",
                "verbose_name_plural": "文书版本",
                "db_table": "document_version",
                "ordering": ["-version"],
                "indexes": [
                    models.Index(
                        fields=["case", "document_type", "version"],
                        name="document_ve_case_id_b39a72_idx",
                    ),
                    models.Index(
                        fields=["workflow_run", "document_type"],
                        name="document_ve_workflo_ae04ca_idx",
                    ),
                ],
            },
        ),
    ]
