# Generated by hand
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_evidence_mask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='标记为示例案例，禁止删除案件及其已有证据', verbose_name='示例案例'),
        ),
    ]
