# -*- coding: utf-8 -*-
"""api 应用路由。"""
from django.urls import path
from rest_framework_simplejwt.views import TokenVerifyView

from api.views import (
    RegisterView,
    RegisterSendCodeView,
    RegisterVerifyCodeView,
    LoginView,
    LoginSendCodeView,
    LoginEmailCodeView,
    PasswordResetSendCodeView,
    PasswordResetVerifyCodeView,
    PasswordResetConfirmView,
    RefreshView,
    LogoutView,
    LogoutAllView,
    CurrentUserView,
    CurrentUserAvatarView,
    UserPreferenceView,
    ChangePasswordSendCodeView,
    ChangePasswordVerifyCodeView,
    ChangePasswordView,
    CurrentEmailSendCodeView,
    CurrentEmailVerifyView,
    EmailChangeRequestView,
    EmailChangeConfirmView,
    UserSessionListView,
    UserSessionDetailView,
    CaseDetailView,
    CaseListCreateView,
    CaseUpdateDeleteView,
    CaseStatusTransitionView,
    CaseArchiveView,
    CaseCancelView,
    CaseStatusLogView,
    CaseWorkflowView,
    CaseWorkflowHistoryView,
    CaseWorkflowReplayView,
    CaseWorkflowPauseView,
    CaseWorkflowCancelView,
    CaseWorkflowStateView,
    CaseWorkflowStartView,
    CaseWorkflowStreamView,
    CaseWorkflowResumeView,
    MaskImageView,
    EvidenceListCreateView,
    EvidenceUploadView,
    EvidenceDeleteView,
    ExtractedFieldListView,
    ExtractedFieldUpdateView,
    TimelineListView,
    TimelineRebuildView,
    TimelineNodeUpdateView,
    ComplaintView,
    ComplaintRegenerateView,
    RespondTemplateView,
    RespondTemplateRegenerateView,
    MaskView,
    ExportView,
    ExportPackageView,
    ExportPDFView,
    CaseTypePresetListView,
    ApplyPresetView,
    StatsView,
    submit_intervention_view,
    # Task 3.2：/workflow-runs/* 新统一接口
    WorkflowRunCreateView,
    WorkflowRunSnapshotView,
    WorkflowRunPauseView,
    WorkflowRunInterventionSubmitView,
    WorkflowRunRetryView,
    WorkflowRunCancelView,
    CaseWorkflowRunsListView,
    # Task 4.1.4：段落级重新生成
    DocumentParagraphRegenerateView,
    # Task 4.2.4：导出前质量门检查
    DocumentExportCheckView,
)

urlpatterns = [
    # 鉴权路由
    path('auth/register/', RegisterView.as_view()),
    path('auth/register/send-code/', RegisterSendCodeView.as_view()),
    path('auth/register/verify-code/', RegisterVerifyCodeView.as_view()),
    path('auth/login/', LoginView.as_view()),
    path('auth/login/send-code/', LoginSendCodeView.as_view()),
    path('auth/login/email-code/', LoginEmailCodeView.as_view()),
    path('auth/password-reset/send-code/', PasswordResetSendCodeView.as_view()),
    path('auth/password-reset/verify-code/', PasswordResetVerifyCodeView.as_view()),
    path('auth/password-reset/confirm/', PasswordResetConfirmView.as_view()),
    path('auth/refresh/', RefreshView.as_view()),
    path('auth/verify/', TokenVerifyView.as_view()),
    path('auth/me/', CurrentUserView.as_view()),
    path('auth/me/avatar/', CurrentUserAvatarView.as_view()),
    path('auth/me/email/send-code/', CurrentEmailSendCodeView.as_view()),
    path('auth/me/email/verify/', CurrentEmailVerifyView.as_view()),
    path('auth/me/email/change/request/', EmailChangeRequestView.as_view()),
    path('auth/me/email/change/confirm/', EmailChangeConfirmView.as_view()),
    path('auth/me/preferences/', UserPreferenceView.as_view()),
    path('auth/change-password/send-code/', ChangePasswordSendCodeView.as_view()),
    path('auth/change-password/verify-code/', ChangePasswordVerifyCodeView.as_view()),
    path('auth/change-password/', ChangePasswordView.as_view()),
    path('auth/logout/', LogoutView.as_view()),
    path('auth/logout-all/', LogoutAllView.as_view()),
    path('auth/sessions/', UserSessionListView.as_view()),
    path('auth/sessions/<int:session_id>/', UserSessionDetailView.as_view()),
    # T1 新增路由
    path('cases/', CaseListCreateView.as_view()),
    path('cases/<int:pk>/manage/', CaseUpdateDeleteView.as_view()),
    path('cases/<int:pk>/status/transition/', CaseStatusTransitionView.as_view()),
    path('cases/<int:pk>/archive/', CaseArchiveView.as_view()),
    path('cases/<int:pk>/cancel/', CaseCancelView.as_view()),
    path('cases/<int:pk>/status-logs/', CaseStatusLogView.as_view()),
    path('cases/<int:pk>/mask-images/', MaskImageView.as_view()),
    path('cases/<int:pk>/export/package/', ExportPackageView.as_view()),
    path('cases/<int:pk>/export/pdf/', ExportPDFView.as_view()),
    path('cases/<int:pk>/run-workflow/', CaseWorkflowView.as_view()),
    path('cases/<int:pk>/workflow/history/', CaseWorkflowHistoryView.as_view()),
    path('cases/<int:pk>/workflow/replay/', CaseWorkflowReplayView.as_view()),
    path('cases/<int:pk>/workflow/pause/', CaseWorkflowPauseView.as_view()),
    path('cases/<int:pk>/workflow/cancel/', CaseWorkflowCancelView.as_view()),
    path('cases/<int:pk>/workflow/state/', CaseWorkflowStateView.as_view()),
    # SSE 工作流流式改造（2026-07-07 新增）
    path('cases/<int:pk>/workflow/start/', CaseWorkflowStartView.as_view()),
    path('cases/<int:pk>/workflow/stream/', CaseWorkflowStreamView.as_view()),
    path('cases/<int:pk>/workflow/resume/', CaseWorkflowResumeView.as_view()),
    # Task 2.4：介入提交占位端点（Task 3.2 迁移到 /workflow-runs/{run_id}/...）
    path('cases/<int:case_id>/interventions/<int:intervention_id>/submit/', submit_intervention_view),
    # 既有路由
    path('cases/<int:pk>/', CaseDetailView.as_view()),
    path('cases/<int:case_id>/evidences/', EvidenceListCreateView.as_view()),
    path('cases/<int:case_id>/evidences/upload/', EvidenceUploadView.as_view()),
    path('evidences/<int:pk>/', EvidenceDeleteView.as_view()),
    path('evidences/<int:evidence_id>/extracted-fields/', ExtractedFieldListView.as_view()),
    path('extracted-fields/<int:pk>/', ExtractedFieldUpdateView.as_view()),
    path('cases/<int:case_id>/timeline/', TimelineListView.as_view()),
    path('cases/<int:case_id>/timeline/rebuild/', TimelineRebuildView.as_view()),
    path('timeline-nodes/<int:pk>/', TimelineNodeUpdateView.as_view()),
    path('cases/<int:case_id>/complaints/', ComplaintView.as_view()),
    path('cases/<int:case_id>/complaints/regenerate/', ComplaintRegenerateView.as_view()),
    path('cases/<int:case_id>/respond-templates/', RespondTemplateView.as_view()),
    path('cases/<int:case_id>/respond-templates/regenerate/', RespondTemplateRegenerateView.as_view()),
    path('cases/<int:case_id>/mask/', MaskView.as_view()),
    path('cases/<int:case_id>/export/', ExportView.as_view()),
    # Task 27：案件模板预设
    path('case-presets/', CaseTypePresetListView.as_view()),
    path('cases/<int:pk>/apply-preset/', ApplyPresetView.as_view()),
    # Task 28：数据统计仪表盘
    path('stats/dashboard/', StatsView.as_view()),
    # ===== Task 3.2：/workflow-runs/* 新统一接口（保留旧 /cases/<id>/workflow/* 兼容）=====
    # SubTask 3.2.1：创建工作流运行（POST /api/cases/{case_id}/workflow-runs/）
    path('cases/<int:case_id>/workflow-runs/', WorkflowRunCreateView.as_view()),
    # SubTask 3.2.7：历史运行列表（GET /api/cases/{case_id}/workflow-runs/list/）
    #   注：与 SubTask 3.2.1 共用同一路径前缀，但用 list/ 后缀避免与 POST 根路径冲突。
    #   GET 默认会路由到 WorkflowRunCreateView（不支持 get 方法），故独立路由。
    path('cases/<int:case_id>/workflow-runs/list/', CaseWorkflowRunsListView.as_view()),
    # SubTask 3.2.2：获取权威快照
    path('workflow-runs/<int:run_id>/snapshot/', WorkflowRunSnapshotView.as_view()),
    # SubTask 3.2.3：请求暂停
    path('workflow-runs/<int:run_id>/pause/', WorkflowRunPauseView.as_view()),
    # SubTask 3.2.4：提交介入（含 409 冲突响应）
    path(
        'workflow-runs/<int:run_id>/interventions/<int:intervention_id>/submit/',
        WorkflowRunInterventionSubmitView.as_view(),
    ),
    # SubTask 3.2.5：局部重跑
    path('workflow-runs/<int:run_id>/retry/', WorkflowRunRetryView.as_view()),
    # SubTask 3.2.6：取消运行
    path('workflow-runs/<int:run_id>/cancel/', WorkflowRunCancelView.as_view()),
    # ===== Task 4.1.4：段落级重新生成（专业文书工作台）=====
    path(
        'workflow-runs/<int:run_id>/documents/<int:document_id>/paragraphs/<str:paragraph_id>/regenerate/',
        DocumentParagraphRegenerateView.as_view(),
        name='document-paragraph-regenerate',
    ),
    # ===== Task 4.2.4：导出前质量门检查 =====
    path(
        'workflow-runs/<int:run_id>/documents/<int:document_id>/export-check/',
        DocumentExportCheckView.as_view(),
        name='document-export-check',
    ),
]
